### ISSUE TITLE
Integration Tests in Travis

### ISSUE THREAD

**Issue by arm4b** [StackStorm/chef-stackstorm#17]
Running Test-Kitchen with Docker driver in Travis would be nice.

So with that for every PR we can be sure that cookbook actually works OK on different platforms (ubuntu-14.04, centos-7.2).

**Comment by jvrplmlmn** [comment]
Related:

https://github.com/zuazo/kitchen-in-travis-native
https://github.com/zuazo/kitchen-in-travis

**Comment by jvrplmlmn** [comment]
Related:

https://github.com/zuazo/kitchen-in-travis-native
https://github.com/zuazo/kitchen-in-travis
