### ISSUE TITLE
Integration Tests (InSpec)

### ISSUE THREAD

**Issue by arm4b** [StackStorm/chef-stackstorm#29]
> Partially adresses https://github.com/StackStorm/chef-stackstorm/issues/26

`Serverspec`/`Inspec` Integration tests would be nice.

There are already some examples to re-use from the:
https://github.com/StackStorm/st2-packages/blob/master/rake/spec/default/60-st2_all-services-ok_spec.rb

**Comment by jvrplmlmn** [comment]
My vote goes for InSpec over Serverspec, because it opens the possibility of reusing the tests for auditing.

**Comment by jvrplmlmn** [comment]
I got started with InSpec tests for the 'stackstorm::user' recipe, see #47

**Comment by arm4b** [comment]
Some thoughts from #47: 

I think in future it would be fine to Test installations with custom settings: somehow re-use initial attributes passed by user OR another approach, - read `/etc/st2/st2.conf` settings like `[system_user]` and more.

So the Integration Test could be self-sufficient and applied not only just for `stackstorm::bundle` with all default parameters but for custom installations.

In future I expect users to run `InSpec` tests for troubleshooting when they experience any Issues with StackStorm Installation.

**Comment by arm4b** [comment]
~On related note, it may be nice to configure the following directory structure for tests:~
* ~`test/unit/...` - ChefSpec~
* ~`test/integration/...` - InSpec~
~This will make things more straightforward.~

**Comment by shortdudey123** [comment]
FWIW, `test/unit/...` is not typically the standard path.  Some cookbooks do it, but most are in the current place (`spec/...`)

**Comment by arm4b** [comment]
Done in https://github.com/StackStorm/chef-stackstorm/pull/61 https://github.com/StackStorm/chef-stackstorm/pull/53 https://github.com/StackStorm/chef-stackstorm/pull/52 https://github.com/StackStorm/chef-stackstorm/pull/51
