### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by arm4b** [StackStorm/chef-stackstorm#36]
* [x] Changelog changes
* [x] Obtain Chef Supermarket credentials
* [x] Get familiar with the process, release `0.5.0` [[ 1 ](https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/RELEASE_PROCESS.MD)]

https://github.com/StackStorm/chef-stackstorm/milestone/1

**Comment by shortdudey123** [comment]
I can release it when we are ready

**Comment by arm4b** [comment]
Thanks!
I'm OK to do that, to get closer to entire process.

**Comment by arm4b** [comment]
Released in https://github.com/StackStorm/chef-stackstorm/releases/tag/v0.5.0 and https://supermarket.chef.io/cookbooks/stackstorm/versions/0.5.0
