### ISSUE TITLE
Lint Checks vs Integration Tests in 2 CIs

### ISSUE THREAD

**Issue by arm4b** [StackStorm/chef-stackstorm#38]
As the codebase and number of different Checks & Tests grows, add another CI to unload Travis from doing Lint Checks & Unit tests (build time in Travis is already `10mins`+).

#### Some different CI (CircleCI, etc)
* [ ] Cookstyle lint
* [ ] Foodcritic lint
* [ ] ChefSpec Unit Tests
* [ ] Sequenced execution

#### Travis: 
* [ ] Test-Kitchen
* [ ] Serverspec, see https://github.com/StackStorm/chef-stackstorm/issues/29
* [ ] Parallel tests across different platforms (Dockerized as is)

_Not a priority though_

**Comment by arm4b** [comment]
In a long term we might still need this when having `5` parallel Test-Kitchen builds in Travis:
- Ubuntu Trusty
- Ubuntu Xenial
- EL6 (?)
- EL7
- Checks + Unit tests

(As I remember Travis has limited number of parallel builds).

Anyways, not a problem for now with https://github.com/StackStorm/chef-stackstorm/pull/39, thanks @shortdudey123 for keeping momentum.

**Comment by shortdudey123** [comment]
There is no limit on concurrent builds on open-source.  They set aside a specific % of infra to do open source vs paid.  If you do a build in the middle of the night US time, you could build 100 builds at the same time but during the day you might wait a couple min for even 1 to start.

See https://travis-ci.com/plans and https://www.traviscistatus.com/ (graphs)

**Comment by arm4b** [comment]
@shortdudey123 You're right, thanks!

**Comment by shortdudey123** [comment]
no problem 😄
