### ISSUE TITLE
platform_version in Travis

### ISSUE THREAD

**Issue by arm4b** [StackStorm/chef-stackstorm#44]
In Travis we see confusing `platform_version` when running ChefSpec unit tests. It's not clear what that really means.
![](https://i.imgur.com/Dpm1gtq.png)

After some research, here is what is `platform_version` and how it should be: 
![](https://i.imgur.com/yfN7XPs.png)

Example found in `mysql` chef cookbook:
- build: https://travis-ci.org/chef-cookbooks/mysql/jobs/172042270
- spec: https://github.com/chef-cookbooks/mysql/blob/master/spec/mysql_server_installation_package_spec.rb

So it might be good to follow that example by running unit tests with different platform settings and remove platform hardcoding from [spec_helper.rb](https://github.com/StackStorm/chef-stackstorm/blob/b980da8be4ed475a279ba6182b799a84f84ace54/spec/spec_helper.rb#L31-L32)

**Comment by shortdudey123** [comment]
nice find!

**Comment by shortdudey123** [comment]
Looks like `yum-erlang_solutions` is the one causing the `platform_version` output as well as the deprecation warnings

**Comment by shortdudey123** [comment]
Solved by https://github.com/chef-cookbooks/yum-erlang_solutions/pull/11

**Comment by arm4b** [comment]
Good catch!

**Comment by shortdudey123** [comment]
PR merged on the yum-erlang_solutions side
Should be picked up in the next supermarket release

**Comment by shortdudey123** [comment]
Looks like it was already released
https://github.com/chef-cookbooks/yum-erlang_solutions/commit/168e72b0d14bf2e20a7d5de960098a444263d1a8

Restarted the `master` branch build on travis and it cleaned up the extra output
https://travis-ci.org/StackStorm/chef-stackstorm/jobs/179058632

**Comment by arm4b** [comment]
Yay! Thanks @shortdudey123, looks much cleaner now :+1: 

I renamed the Issue just not to open another one, related to [multi-platform Unit Testing](https://camo.githubusercontent.com/c688982e9d38de2c5bcc9d2bf99b6ecb3da3a23c/68747470733a2f2f692e696d6775722e636f6d2f79664e375850732e706e67).

But you can close this Issue as "resolved" & open another one with the correct description, if you want.
