### ISSUE TITLE
CI is broken on CentOS7

### ISSUE THREAD

**Issue by arm4b** [StackStorm/chef-stackstorm#58]
Restarted the Travis build for `master` and `CentOS7` looks like started to fail: https://travis-ci.org/StackStorm/chef-stackstorm/jobs/182408367

Probably kind of upstream changes in Mongo cookbook dependency or in Docker image.
Something to research.

**Comment by shortdudey123** [comment]
Doubt its the upstream cookbooks since `mongo3` last changed over 4 months ago
Probably some obscure dependency

**Comment by shortdudey123** [comment]
Interestingly enough, CentOS 7 on vagrant under test-kitchen passes fine

**Comment by arm4b** [comment]
Not an issue anymore, probably something fixed in upstream `centos:7` Docker image. Anyways, now it works: 

https://travis-ci.org/StackStorm/chef-stackstorm/builds/184337644
