### ISSUE TITLE
Switch to MongoDB 3.2

### ISSUE THREAD

**Issue by arm4b** [StackStorm/chef-stackstorm#8]
Since StackStorm `v1.6` MongoDB `3.2` is the default version,
see: https://docs.stackstorm.com/install/deb.html#install-dependencies for installation instructions.

Reflect the change in st2 Configuration Management repos (same is for https://github.com/StackStorm/ansible-st2/issues/49).

**Comment by shortdudey123** [comment]
Cookbook would need to switch from `mongodb` to `mongodb3`
